let s:conf_dir = $HOME.'/.config/vim'
let s:state_dir = $HOME.'/.local/share/vim'
let s:undo_dir = s:state_dir.'/undo'
let s:swap_dir = s:state_dir.'/swap'
let s:backup_dir = s:state_dir.'/backup'

if !isdirectory(s:swap_dir) | call mkdir(s:swap_dir, "p") | endif
if !isdirectory(s:undo_dir) | call mkdir(s:undo_dir, "p") | endif
if !isdirectory(s:backup_dir) | call mkdir(s:backup_dir, "p") | endif

let &runtimepath=substitute(&runtimepath, '\('.$HOME.'\|\~\)/.vim', s:conf_dir, "g")
let &packpath=substitute(&runtimepath, '\('.$HOME.'\|\~\)/.vim', s:conf_dir, "g")
let &viminfofile=s:state_dir."/viminfo"
let &directory=s:swap_dir
let &undodir=s:undo_dir
let &backupdir=s:backup_dir
let g:netrw_home=s:state_dir

runtime settings.vim
runtime mappings.vim
runtime statusline.vim
" runtime lsp.vim
